// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ASS.hxx

#ifndef PROTOBUF_ASS_2ehxx__INCLUDED
#define PROTOBUF_ASS_2ehxx__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ASS_2ehxx();
void protobuf_AssignDesc_ASS_2ehxx();
void protobuf_ShutdownFile_ASS_2ehxx();

class PBRequest;
class PBResponse;

// ===================================================================

class PBRequest : public ::google::protobuf::Message {
 public:
  PBRequest();
  virtual ~PBRequest();

  PBRequest(const PBRequest& from);

  inline PBRequest& operator=(const PBRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBRequest& default_instance();

  void Swap(PBRequest* other);

  // implements Message ----------------------------------------------

  PBRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PBRequest& from);
  void MergeFrom(const PBRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 header = 1;
  inline bool has_header() const;
  inline void clear_header();
  static const int kHeaderFieldNumber = 1;
  inline ::google::protobuf::uint32 header() const;
  inline void set_header(::google::protobuf::uint32 value);

  // required uint32 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);

  // required bytes message = 3;
  inline bool has_message() const;
  inline void clear_message();
  static const int kMessageFieldNumber = 3;
  inline const ::std::string& message() const;
  inline void set_message(const ::std::string& value);
  inline void set_message(const char* value);
  inline void set_message(const void* value, size_t size);
  inline ::std::string* mutable_message();
  inline ::std::string* release_message();
  inline void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:PBRequest)
 private:
  inline void set_has_header();
  inline void clear_has_header();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_message();
  inline void clear_has_message();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 header_;
  ::google::protobuf::uint32 id_;
  ::std::string* message_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_ASS_2ehxx();
  friend void protobuf_AssignDesc_ASS_2ehxx();
  friend void protobuf_ShutdownFile_ASS_2ehxx();

  void InitAsDefaultInstance();
  static PBRequest* default_instance_;
};
// -------------------------------------------------------------------

class PBResponse : public ::google::protobuf::Message {
 public:
  PBResponse();
  virtual ~PBResponse();

  PBResponse(const PBResponse& from);

  inline PBResponse& operator=(const PBResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBResponse& default_instance();

  void Swap(PBResponse* other);

  // implements Message ----------------------------------------------

  PBResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PBResponse& from);
  void MergeFrom(const PBResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 header = 1;
  inline bool has_header() const;
  inline void clear_header();
  static const int kHeaderFieldNumber = 1;
  inline ::google::protobuf::uint32 header() const;
  inline void set_header(::google::protobuf::uint32 value);

  // required uint32 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);

  // required bool result = 3;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 3;
  inline bool result() const;
  inline void set_result(bool value);

  // @@protoc_insertion_point(class_scope:PBResponse)
 private:
  inline void set_has_header();
  inline void clear_has_header();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 header_;
  ::google::protobuf::uint32 id_;
  bool result_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_ASS_2ehxx();
  friend void protobuf_AssignDesc_ASS_2ehxx();
  friend void protobuf_ShutdownFile_ASS_2ehxx();

  void InitAsDefaultInstance();
  static PBResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// PBRequest

// required uint32 header = 1;
inline bool PBRequest::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PBRequest::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PBRequest::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PBRequest::clear_header() {
  header_ = 0u;
  clear_has_header();
}
inline ::google::protobuf::uint32 PBRequest::header() const {
  return header_;
}
inline void PBRequest::set_header(::google::protobuf::uint32 value) {
  set_has_header();
  header_ = value;
}

// required uint32 id = 2;
inline bool PBRequest::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PBRequest::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PBRequest::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PBRequest::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 PBRequest::id() const {
  return id_;
}
inline void PBRequest::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
}

// required bytes message = 3;
inline bool PBRequest::has_message() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PBRequest::set_has_message() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PBRequest::clear_has_message() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PBRequest::clear_message() {
  if (message_ != &::google::protobuf::internal::kEmptyString) {
    message_->clear();
  }
  clear_has_message();
}
inline const ::std::string& PBRequest::message() const {
  return *message_;
}
inline void PBRequest::set_message(const ::std::string& value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  message_->assign(value);
}
inline void PBRequest::set_message(const char* value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  message_->assign(value);
}
inline void PBRequest::set_message(const void* value, size_t size) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  message_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PBRequest::mutable_message() {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  return message_;
}
inline ::std::string* PBRequest::release_message() {
  clear_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = message_;
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void PBRequest::set_allocated_message(::std::string* message) {
  if (message_ != &::google::protobuf::internal::kEmptyString) {
    delete message_;
  }
  if (message) {
    set_has_message();
    message_ = message;
  } else {
    clear_has_message();
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// PBResponse

// required uint32 header = 1;
inline bool PBResponse::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PBResponse::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PBResponse::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PBResponse::clear_header() {
  header_ = 0u;
  clear_has_header();
}
inline ::google::protobuf::uint32 PBResponse::header() const {
  return header_;
}
inline void PBResponse::set_header(::google::protobuf::uint32 value) {
  set_has_header();
  header_ = value;
}

// required uint32 id = 2;
inline bool PBResponse::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PBResponse::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PBResponse::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PBResponse::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 PBResponse::id() const {
  return id_;
}
inline void PBResponse::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
}

// required bool result = 3;
inline bool PBResponse::has_result() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PBResponse::set_has_result() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PBResponse::clear_has_result() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PBResponse::clear_result() {
  result_ = false;
  clear_has_result();
}
inline bool PBResponse::result() const {
  return result_;
}
inline void PBResponse::set_result(bool value) {
  set_has_result();
  result_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ASS_2ehxx__INCLUDED
